name: Siloka Release Firebase App Distribution

on:
  release:
    types:
      - published

jobs:
  release:
    if: ${{ github.event }} == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: trust /github/workspace
        run:
          git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build release
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Release
          file: app/build/outputs/apk/debug/app-debug.apk
