name: Run ktlint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: ktlint
        run: ./gradlew ktlintCheck

      - uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: ./**/build/reports/ktlint/
